### ISSUE TITLE
Revised default file extensions

### ISSUE THREAD

**Issue by donaldoakes** [ply-ct/ply#27]
Underlying file formats do not change, but extensions will be as follows.

Ply request files:
  - `*.ply.yaml` becomes `*.ply`

Flows:
  - `*.ply.flow` becomes `*.flow`

Expected and actual results:
  - `*.yaml` becomes `*.ply-result` (or just `*.result`, or stay with `*.yaml`?)

This will prepare us for having a custom vscode editor for Ply request files.

Update ply-demo and the docs to reflect these new conventions.

**Comment by magrawa** [comment]
I agree with simplifying the extension. I think we should go with *.result.
